Fixed bof delta from iacv1

diff --git a/gitlab_templates/switch-iac/.gitlab-ci.yml b/gitlab_templates/switch-iac/.gitlab-ci.yml
--- a/gitlab_templates/switch-iac/.gitlab-ci.yml
+++ b/gitlab_templates/switch-iac/.gitlab-ci.yml
@@ -1,6 +1,6 @@
 default: 
   image: 
-    name: ghcr.io/mojaloop/iac-aws-platform:2.0.1-beta1
+    name: ghcr.io/mojaloop/iac-aws-platform:2.0.3
   before_script:
     - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
     - export BUCKET=$(grep bucket backend.hcl | cut -f2 -d '=' | tr -d '"' | xargs)
@@ -596,6 +596,18 @@ Create Gateway Cluster:
       - ${CI_PROJECT_DIR}/ttk-goldenpath-report.html
   when: manual
 
+6. Run RBAC Tests:
+  stage: "Run Tests"
+  script:
+    - helm --kubeconfig=admin-gateway.conf test bof --filter name=bof-rbac-tests -n mojaloop --logs
+  when: manual
+
+7. Run Report Tests:
+  stage: "Run Tests"
+  script:
+    - helm --kubeconfig=admin-gateway.conf test bof --filter name=bof-report-tests -n mojaloop --logs
+  when: manual
+
 1. Run External PM4ML Onboarding:
   stage: "Maintain Platform"
   script:
@@ -616,11 +628,27 @@ Create Gateway Cluster:
 3. Update mojaloop roles:
   stage: "Maintain Platform"
   script:
+    - |
+      private_subdomain=$(terraform output -state=terraform.tfstate private_subdomain | tr -d '"');
+      validation_api_url=http://bofapi.${private_subdomain}/operator/validate/role-permissions;
+      echo ${validation_api_url};
+      mojaloop_roles=`cat ./bof-custom-resources/role-permissions/mojaloop-roles.json`;
+      permission_exclusions=`cat ./bof-custom-resources/role-permissions/permission-exclusions.json`;
+      request_body='{ "rolePermissions":'${mojaloop_roles}',"permissionExclusions":'${permission_exclusions}'}';
+      response_code=$(curl -s -X POST ${validation_api_url} -H 'Content-Type: application/json' -d "${request_body}" -w "%{http_code}" -o response_body.txt);
+      if [ $response_code != 200 ]; then echo "VALIDATION FAILED"; cat response_body.txt; exit 1; else echo "VALIDATION PASSED"; fi;
     - cd $CI_IMAGE_PROJECT_DIR/terraform/k8s-setup/mojaloop-roles
     - terraform init -backend-config ${CI_PROJECT_DIR}/backend.hcl
     - terraform apply -auto-approve -var="project_root_path=$CI_IMAGE_PROJECT_DIR"
   when: manual
 
+4. Update custom reports:
+  stage: "Maintain Platform"
+  script:
+    - cd $CI_IMAGE_PROJECT_DIR/terraform/k8s-setup/mojaloop-custom-reports
+    - terraform init -backend-config ${CI_PROJECT_DIR}/backend.hcl
+    - terraform apply -auto-approve -var="project_root_path=$CI_IMAGE_PROJECT_DIR"
+  when: manual
 
 11. Gateway K8S Cluste Deployments:
   stage: "Run Tests"
